# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    param_fetcher_listener: true
    body_listener: true
    format_listener:
        enabled: true
        rules:
            - { path: '^/api/', priorities: [ 'json' ], fallback_format: 'json' }
    versioning: false
    view:
        view_response_listener: 'force'
    serializer:
        serialize_null: true
