version: '2'

services:

  nginx:
    build:
      context: ./Docker/Config/Nginx
    ports:
      - 80:80
    volumes_from:
      - php
    volumes:
      - ./Docker/Config/Nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php

  php:
    build:
      context: ./Docker/Config/PHP
      args:
        TIMEZONE: Europe/London
    volumes:
      - ./:/code
    links:
      - database

  database:
    build:
      context: ./Docker/Config/MySQL
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ./Docker/Data/database:/var/lib/mysql
